
import { Board } from "../src/Board.mjs";
import { expect } from "chai";


describe("Clear lines to empty board", () => {
  let board;
  beforeEach(() => {
    board = new Board(10, 6);
  });

  it("Clear single line", () => {
    board.setBoard(
     `..........
      ..........
      ..........
      ..........
      ..........
      TTTTTTTTTT`
   )

    board.clear()

    expect(board.toString()).to.equalShape(
     `..........
      ..........
      ..........
      ..........
      ..........
      ..........`
    );
  });

  it("Clear two lines", () => {
    board.setBoard(
     `..........
      ..........
      ..........
      ..........
      TTTTTTTTTT
      TTTTTTTTTT`
   )

    board.clear()

    expect(board.toString()).to.equalShape(
     `..........
      ..........
      ..........
      ..........
      ..........
      ..........`
    );
  });

});

describe("Clear lines to empty board", () => {
  let board;
  beforeEach(() => {
    board = new Board(10, 6);
  });

  it(" rows above drop when line cleared", () => {
    board.setBoard(
     `..........
      ..........
      ...T......
      ..........
      .....T....
      TTTTTTTTTT`
   )

    board.clear()

    expect(board.toString()).to.equalShape(
     `..........
      ..........
      ..........
      ...T......
      ..........
      .....T....`
    );
  });

  it("rows above drop twice when two lines cleared", () => {
    board.setBoard(
     `..........
      ...T......
      ..........
      .....T....
      TTTTTTTTTT
      TTTTTTTTTT`
   )

    board.clear()

    expect(board.toString()).to.equalShape(
     `..........
      ..........
      ..........
      ...T......
      ..........
      .....T....`
    );
  });

});

